import os

# NON-STANDARD LIBRARY: 'vcdvcd' is used here to parse the binary .vcd waveform files.
# It is not built into Python, so it must be installed via: pip install vcdvcd
try:
    from vcdvcd import VCDVCD
except ImportError:
    VCDVCD = None

def parse_vcd_to_text(vcd_file: str, start_time: int = 0, end_time: int = None) -> str:
    """
    Parses a VCD (Value Change Dump) file and converts it into an ASCII text table.
    This allows LLMs to "read" waveforms without needing image processing.
    
    Args:
        vcd_file (str): Path to the .vcd file generated by ModelSim/VCS.
        start_time (int): The simulation time to start reading from.
        end_time (int): The simulation time to stop reading. If None, reads to the end.
        
    Returns:
        str: A formatted text table of the signals, or an error message.
    """
    if VCDVCD is None:
        return "Execution Error: The 'vcdvcd' library is missing. Please run 'pip install vcdvcd'."

    if not os.path.exists(vcd_file):
        return f"Execution Error: The file '{vcd_file}' was not found in the current directory."

    try:
        # Load the VCD file into memory
        vcd = VCDVCD(vcd_file)
        
        # Get the names of all signals in the waveform (e.g., 'clk', 'reset', 'q')
        signal_names = vcd.get_signals()
        if not signal_names:
            return f"Execution Error: No signals found in {vcd_file}."

        # Keep track of the current value of each signal. Default to 'x' (unknown)
        current_state = {sig: 'x' for sig in signal_names}
        
        # vcdvcd stores data as time-value pairs. We need to organize it chronologically.
        # time_events will map a specific time to a list of signal changes: { time: [(sig_name, new_val)] }
        time_events = {}
        for sig in signal_names:
            # tv is a list of tuples: (timestamp, value)
            for time, val in vcd[sig].tv:
                if time not in time_events:
                    time_events[time] = []
                time_events[time].append((sig, val))
                
        # Sort all the timestamps so we can walk through time linearly
        sorted_times = sorted(time_events.keys())
        
        # Prepare the output table
        output_lines = []
        
        # Create the Header Row (e.g., "Time | clk | reset | d | q")
        header = "Time\t| " + " | ".join(signal_names)
        output_lines.append(header)
        output_lines.append("-" * len(header))
        
        # Walk through the simulation chronologically
        for t in sorted_times:
            # Update our current state dictionary with any signals that changed at this exact timestamp
            for sig, val in time_events[t]:
                current_state[sig] = val
                
            # Only record the state in our output table if it falls within the requested time window
            if t >= start_time and (end_time is None or t <= end_time):
                # Build the row showing the values of all signals at time 't'
                row_values = [current_state[sig] for sig in signal_names]
                row = f"{t}\t| " + " | ".join(row_values)
                output_lines.append(row)
                
        # If no events happened in the time window, let the LLM know
        if len(output_lines) == 2:
            return f"No signal changes occurred between time {start_time} and {end_time if end_time else 'end'}."

        # Combine all lines into a single multi-line string
        return "\n".join(output_lines)

    except Exception as e:
        return f"System Error: An unexpected error occurred while parsing the VCD file: {str(e)}"

# ==========================================
# Example usage / Testing the tool locally
# ==========================================
if __name__ == "__main__":
    # Example: If you have a 'dump.vcd' file from a ModelSim simulation, 
    # you would call it like this to see signals between 10ns and 50ns:
    
    test_file = "test02.vcd"
    
    # We only run the test if a dummy VCD file actually exists
    if os.path.exists(test_file):
        print(f"--- Parsing Waveforms from {test_file} ---")
        # Extract the waveforms between time 0 and 100
        text_waveform = parse_vcd_to_text(test_file, start_time=0, end_time=100)
        print(text_waveform)
    else:
        print(f"Note: Run a simulation to generate '{test_file}' to test this script locally.")