
import os
from autogen_agentchat.agents import AssistantAgent
from autogen_ext.models.anthropic import AnthropicChatCompletionClient

def write_debug_report(filepath: str, content: str) -> str:
    """
    Writes the detailed debug and root-cause analysis report to the disk.
    """
    try:
        os.makedirs(os.path.dirname(filepath), exist_ok=True)
        with open(filepath, "w") as f:
            f.write(content)
        return f"Success: Wrote detailed debug report to {filepath}"
    except Exception as e:
        return f"Error writing debug report to file: {str(e)}"

def create_debug_agent(model_client: AnthropicChatCompletionClient) -> AssistantAgent:
    """
    Initializes and returns the Debug Agent.
    This agent acts as the analytical brain, comparing expected vs. actual outputs
    and hypothesizing the root cause of RTL bugs.
    """
    debug_system_message = """
    You are a Senior VLSI Debug Engineer. 
    Your job is to analyze failed RTL simulations and provide actionable fixes.
    
    The Orchestrator will provide you with a prompt containing:
    1. The Design Specification.
    2. The Test Stimulus (inputs driven into the design).
    3. The Expected Output (generated by the Python Reference Model).
    4. The Actual Output (parsed ASCII table from the VCD waveform file).
    
    Your Process:
    1. Compare the Actual Output (VCD) against the Expected Output (Reference Model) cycle-by-cycle.
    2. Identify the exact timestamp/cycle where the mismatch first occurs.
    3. Cross-reference the mismatch with the Design Specification to hypothesize the logical bug in the RTL.
    4. Write a highly detailed "Debug Report" containing:
        - Error Summary
        - Cycle-by-cycle comparison table highlighting the failure
        - Root Cause Hypothesis
        - Suggested RTL Fix
    5. Use the `write_debug_report(filepath, content)` tool to save this report as a text/markdown file (e.g., 'work/debug_report.md').
    6. Once the report is successfully saved, reply with exactly "TERMINATE".
    """

    agent = AssistantAgent(
        name="Debug_Agent",
        model_client=model_client,
        system_message=debug_system_message,
        tools=[write_debug_report], 
    )
    
    return agent

# ==========================================
# Example usage / Testing the agent locally
# ==========================================
if __name__ == "__main__":
    import asyncio
    from autogen_agentchat.teams import RoundRobinGroupChat
    from autogen_agentchat.conditions import TextMentionTermination, MaxMessageTermination
    from autogen_agentchat.ui import Console
    from dotenv import load_dotenv

    load_dotenv()
    
    async def test_debug_agent():
        client = AnthropicChatCompletionClient(
            model="claude-3-5-sonnet-20240620",
            api_key=os.environ.get("ANTHROPIC_API_KEY")
        )
        
        debug_agent = create_debug_agent(client)
        termination = TextMentionTermination("TERMINATE") | MaxMessageTermination(5)
        team = RoundRobinGroupChat([debug_agent], termination_condition=termination)
        
        # Mock inputs that the Orchestrator would normally assemble from the other tools/agents
        mock_failure_context = """
        Please analyze this simulation failure:
        
        1. DESIGN SPEC: ALU that acts as a D-Flip Flop (q <= d on posedge clk).
        
        2. TEST STIMULUS:
        Time 0: clk=0, d=0
        Time 10: clk=1, d=1
        
        3. EXPECTED OUTPUT (Ref Model):
        Time 10: q=1
        
        4. ACTUAL OUTPUT (VCD Parser):
        Time | clk | d | q
        0    |  0  | 0 | 0
        10   |  1  | 1 | 0
        """
        
        print("Starting Debug Agent Test...\n")
        await Console(team.run_stream(task=mock_failure_context))

    asyncio.run(test_debug_agent())